{% set version = "0.9.18" %}

package:
  name: lmdb
  version: {{ version }}

source:
  fn: LMDB_{{ version }}.tar.gz
  url: https://github.com/LMDB/lmdb/archive/LMDB_{{ version }}.tar.gz
  sha1: 375e31bd0a4d8426e5fc4bfdb00d532c206d4f2b
  patches:
    - Makefile.patch # [not win]
    - lmdb_45a88275d2a410e683bae4ef44881e0f55fa3c4d.patch # [win]
build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc10 # [win and py34]
    - vc14 # [win and py35]

requirements:
  build:
    - cmake # [win]
    - ninja # [win]

test:
  commands:
    - mdb_copy -V                                    # [unix]
    - mdb_dump -V                                    # [unix]
    - mdb_load -V                                    # [unix]
    - mdb_stat -V                                    # [unix]
    - test -f ${PREFIX}/lib/liblmdb.a                # [unix]
    - test -f ${PREFIX}/lib/liblmdb.so               # [unix]

about:
  home: http://symas.com/mdb/
  license: OpenLDAP Public License
  summary: A high-performance embedded transactional key-value store database.

extra:
  recipe-maintainers:
    - jakirkham
